theme: jekyll-theme-hacker
title: This is ekubot's website.
description: ekubot (stylized in lowercase) is a bot named and modeled after Ekubo, or Dimple, from the anime Mob Psycho 100. Ekubo is a sarcastic and self-centered spirit that acts almost as a spirit guide. Maybe you'll let this bot be yours?
